"""Markdown exporter for research reports."""

import os
from typing import Optional
from pathlib import Path
from models.report import ResearchReport


class MarkdownExporter:
    """Export research reports to Markdown format."""

    def __init__(self, output_dir: str = "outputs"):
        """
        Initialize the Markdown exporter.

        Args:
            output_dir: Directory to save exported reports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def export(
        self,
        report: ResearchReport,
        filename: Optional[str] = None
    ) -> str:
        """
        Export a report to Markdown.

        Args:
            report: The ResearchReport to export
            filename: Optional filename (defaults to topic-based name)

        Returns:
            Path to the exported file
        """
        # Generate markdown content
        markdown = self._generate_markdown(report)

        # Determine filename
        if filename is None:
            # Sanitize topic for filename
            safe_topic = "".join(
                c if c.isalnum() or c in (' ', '-', '_') else '_'
                for c in report.topic
            )
            safe_topic = safe_topic[:50]  # Limit length
            filename = f"{safe_topic.strip().replace(' ', '_')}.md"

        # Write to file
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(markdown)

        return str(filepath)

    def _generate_markdown(self, report: ResearchReport) -> str:
        """Generate Markdown content from a report."""
        lines = []

        # Title
        lines.append(f"# {report.topic}\n")

        # Metadata
        if report.metadata:
            timestamp = report.metadata.get("timestamp", "N/A")
            model = report.metadata.get("model", "N/A")
            lines.append(f"*Generated: {timestamp} | Model: {model}*\n")

        lines.append("---\n")

        # TL;DR
        lines.append("## TL;DR\n")
        lines.append(f"{report.tldr}\n")
        lines.append("---\n")

        # Key Findings
        lines.append("## Key Findings\n")
        if report.key_findings:
            for i, finding in enumerate(report.key_findings, 1):
                lines.append(f"\n### {i}. {finding.finding}\n")
                if finding.citations:
                    lines.append("\n**Sources:**")
                    for citation in finding.citations:
                        lines.append(f"- {citation}")
                    lines.append("")
        else:
            lines.append("*No key findings available.*\n")

        lines.append("---\n")

        # Conflicts and Caveats
        lines.append("## Conflicts & Caveats\n")
        if report.conflicts_and_caveats:
            lines.append(f"{report.conflicts_and_caveats}\n")
        else:
            lines.append("*No conflicts or caveats identified.*\n")

        lines.append("---\n")

        # Top Sources
        lines.append("## Top Sources\n")
        if report.top_sources:
            for i, source in enumerate(report.top_sources, 1):
                lines.append(f"\n### {i}. [{source.title}]({source.url})\n")

                if source.score is not None:
                    lines.append(f"**Relevance Score:** {source.score:.4f}\n")

                if source.why_matters:
                    lines.append(f"**Why It Matters:** {source.why_matters}\n")

                if source.snippet:
                    lines.append(f"\n**Excerpt:**")
                    lines.append(f"> {source.snippet}\n")
        else:
            lines.append("*No sources available.*\n")

        lines.append("---\n")

        # Footer
        lines.append("\n*This report was generated by ScholarAI.*\n")

        return "\n".join(lines)

    def to_string(self, report: ResearchReport) -> str:
        """
        Convert report to Markdown string without saving to file.

        Args:
            report: The ResearchReport to convert

        Returns:
            Markdown formatted string
        """
        return self._generate_markdown(report)


def export_to_markdown(
    report: ResearchReport,
    output_dir: str = "outputs",
    filename: Optional[str] = None
) -> str:
    """
    Convenience function to export a report to Markdown.

    Args:
        report: The ResearchReport to export
        output_dir: Directory to save the report
        filename: Optional filename

    Returns:
        Path to the exported file
    """
    exporter = MarkdownExporter(output_dir=output_dir)
    return exporter.export(report, filename=filename)


def to_markdown(report: ResearchReport) -> str:
    """
    Convert report to Markdown string.

    Args:
        report: The ResearchReport to convert

    Returns:
        Markdown formatted string
    """
    exporter = MarkdownExporter()
    return exporter.to_string(report)
