"""
Export utilities for converting ResearchReport to different formats.

This module provides clean, professional export formats for sharing
research reports in Markdown or JSON.
"""

import json
from pathlib import Path
from typing import Union
from datetime import datetime
import sys
sys.path.append('/home/claude/scholarai-beginner')

from src.agents.synthesizer import ResearchReport
from src.config import Config


class MarkdownExporter:
    """
    Export ResearchReport to Markdown format.
    
    Creates a clean, readable Markdown document suitable for:
    - GitHub/GitLab documentation
    - Academic note-taking systems (Obsidian, Notion)
    - Blog posts or articles
    - PDF conversion via pandoc
    """
    
    @staticmethod
    def export(report: ResearchReport) -> str:
        """
        Convert ResearchReport to Markdown string.
        
        Args:
            report: ResearchReport object to export
        
        Returns:
            Formatted Markdown string
        """
        lines = []
        
        # Title and metadata
        lines.append(f"# {report.topic}\n")
        lines.append(f"*Research Report Generated: {report.synthesis_date}*\n")
        lines.append("---\n")
        
        # TL;DR section
        lines.append("## 📋 Executive Summary (TL;DR)\n")
        lines.append(f"{report.tldr}\n")
        lines.append("---\n")
        
        # Key Findings section
        lines.append("## 🔍 Key Findings\n")
        for i, finding in enumerate(report.key_findings, 1):
            lines.append(f"### {i}. {finding['finding'].split('.')[0]}\n")
            lines.append(f"{finding['finding']}\n")
            lines.append(f"**Citation:** {finding['citation']}\n")
        lines.append("---\n")
        
        # Conflicts and Caveats section
        lines.append("## ⚠️ Conflicts & Caveats\n")
        lines.append(f"{report.conflicts_and_caveats}\n")
        lines.append("---\n")
        
        # Top Sources section
        lines.append("## 📚 Top Sources\n")
        for i, source in enumerate(report.top_sources, 1):
            lines.append(f"### {i}. [{source['title']}]({source['url']})\n")
            lines.append(f"**Why it matters:** {source['why_matters']}\n")
        
        # Footer
        lines.append("\n---")
        lines.append("\n*Generated by ScholarAI Research Assistant*")
        
        return "\n".join(lines)
    
    @staticmethod
    def save(report: ResearchReport, filename: Union[str, Path]) -> Path:
        """
        Save ResearchReport to Markdown file.
        
        Args:
            report: ResearchReport object to export
            filename: Output filename (can be str or Path)
        
        Returns:
            Path to saved file
        """
        # Ensure output directory exists
        Config.ensure_output_dir()
        
        # Convert filename to Path and ensure .md extension
        filepath = Path(filename)
        if filepath.suffix != ".md":
            filepath = filepath.with_suffix(".md")
        
        # If no directory specified, use default output directory
        if not filepath.is_absolute() and filepath.parent == Path("."):
            filepath = Config.OUTPUT_DIR / filepath
        
        # Export and save
        markdown_content = MarkdownExporter.export(report)
        filepath.write_text(markdown_content, encoding="utf-8")
        
        print(f"✓ Markdown report saved: {filepath}")
        return filepath


class JSONExporter:
    """
    Export ResearchReport to JSON format.
    
    Creates structured JSON suitable for:
    - API responses
    - Database storage
    - Further programmatic processing
    - Integration with other tools
    """
    
    @staticmethod
    def export(report: ResearchReport, pretty: bool = True) -> str:
        """
        Convert ResearchReport to JSON string.
        
        Args:
            report: ResearchReport object to export
            pretty: If True, format with indentation
        
        Returns:
            JSON string
        """
        data = report.to_dict()
        
        if pretty:
            return json.dumps(data, indent=2, ensure_ascii=False)
        else:
            return json.dumps(data, ensure_ascii=False)
    
    @staticmethod
    def save(
        report: ResearchReport,
        filename: Union[str, Path],
        pretty: bool = True
    ) -> Path:
        """
        Save ResearchReport to JSON file.
        
        Args:
            report: ResearchReport object to export
            filename: Output filename
            pretty: If True, format with indentation
        
        Returns:
            Path to saved file
        """
        # Ensure output directory exists
        Config.ensure_output_dir()
        
        # Convert filename to Path and ensure .json extension
        filepath = Path(filename)
        if filepath.suffix != ".json":
            filepath = filepath.with_suffix(".json")
        
        # If no directory specified, use default output directory
        if not filepath.is_absolute() and filepath.parent == Path("."):
            filepath = Config.OUTPUT_DIR / filepath
        
        # Export and save
        json_content = JSONExporter.export(report, pretty=pretty)
        filepath.write_text(json_content, encoding="utf-8")
        
        print(f"✓ JSON report saved: {filepath}")
        return filepath


class ReportExporter:
    """
    Unified interface for exporting reports to multiple formats.
    
    This class provides a simple API for exporting to both formats
    or choosing a specific format.
    """
    
    @staticmethod
    def export_all(
        report: ResearchReport,
        base_filename: str
    ) -> dict[str, Path]:
        """
        Export report to all formats.
        
        Args:
            report: ResearchReport to export
            base_filename: Base filename (without extension)
        
        Returns:
            Dictionary mapping format names to file paths
        """
        # Generate safe filename from report topic
        safe_filename = base_filename or ReportExporter._sanitize_filename(
            report.topic
        )
        
        # Export to both formats
        markdown_path = MarkdownExporter.save(report, safe_filename)
        json_path = JSONExporter.save(report, safe_filename)
        
        return {
            "markdown": markdown_path,
            "json": json_path
        }
    
    @staticmethod
    def export_to_format(
        report: ResearchReport,
        format: str,
        filename: str
    ) -> Path:
        """
        Export to a specific format.
        
        Args:
            report: ResearchReport to export
            format: 'markdown' or 'json'
            filename: Output filename
        
        Returns:
            Path to saved file
        """
        if format.lower() in ["markdown", "md"]:
            return MarkdownExporter.save(report, filename)
        elif format.lower() == "json":
            return JSONExporter.save(report, filename)
        else:
            raise ValueError(f"Unknown format: {format}")
    
    @staticmethod
    def _sanitize_filename(text: str) -> str:
        """
        Create a safe filename from text.
        
        Args:
            text: Text to convert to filename
        
        Returns:
            Safe filename string
        """
        # Remove/replace problematic characters
        safe = "".join(c if c.isalnum() or c in " -_" else "_" for c in text)
        # Collapse multiple spaces/underscores
        safe = "_".join(safe.split())
        # Limit length
        safe = safe[:100]
        # Add timestamp to ensure uniqueness
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"{safe}_{timestamp}"


def to_markdown(report: ResearchReport) -> str:
    """Convenience function for exporting to Markdown string."""
    return MarkdownExporter.export(report)


def to_json(report: ResearchReport, pretty: bool = True) -> str:
    """Convenience function for exporting to JSON string."""
    return JSONExporter.export(report, pretty=pretty)


if __name__ == "__main__":
    # Test exporters
    print("Testing Export utilities...")
    
    # Create a mock report for testing
    from src.agents.synthesizer import ResearchReport
    
    mock_report = ResearchReport(
        topic="Testing Export Functionality",
        tldr="This is a test report to demonstrate export capabilities.",
        key_findings=[
            {
                "finding": "Export to Markdown works correctly.",
                "citation": "[1]"
            },
            {
                "finding": "Export to JSON preserves structure.",
                "citation": "[2]"
            }
        ],
        conflicts_and_caveats="No conflicts in test data.",
        top_sources=[
            {
                "title": "Test Source 1",
                "url": "https://example.com/1",
                "why_matters": "Demonstrates source formatting"
            }
        ],
        synthesis_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    
    # Test Markdown export
    print("\n" + "="*60)
    print("MARKDOWN EXPORT")
    print("="*60)
    print(to_markdown(mock_report))
    
    # Test JSON export
    print("\n" + "="*60)
    print("JSON EXPORT")
    print("="*60)
    print(to_json(mock_report))
    
    # Test file saving
    try:
        paths = ReportExporter.export_all(mock_report, "test_report")
        print("\n✓ Files saved successfully:")
        for format_name, path in paths.items():
            print(f"   {format_name}: {path}")
    except Exception as e:
        print(f"Error saving files: {e}")
